lpt_drv: rename inb/outb function pointers
Avoid compilation issues on arm7l (raspberry pi), e.g.:

ksbiglpt.c:1123:949: error: expected identifier before ‘(’ token

Apparently inb() and outb() in struct private_data must conflict with
a macro or something, so change the name of those structure members
to pp_inb() and pp_outb().